"""
Generates a new model
"""
import sys
import subprocess
import os

from pyecore.resources import ResourceSet
from pyecoregen.ecore import EcoreGenerator
import pyecore.type  # We register the XML types (generated by pyecoregen)

# We open the metamodel
rset = ResourceSet()
mm_root = rset.get_resource('pygeppetto/ecore/geppettoModel.ecore').contents[0]

base_path = sys.argv[1] if len(sys.argv) > 1 else 'generated'
model_path = os.path.join(base_path, 'pygeppetto')
if not os.path.exists(model_path):
    os.makedirs(model_path)
# We generate the code using the EcoreGenerator
EcoreGenerator(auto_register_package=True).generate(mm_root, outfolder=model_path)

subprocess.run(['git', 'init'], cwd=base_path)
subprocess.run('git add .'.split(' '), cwd=base_path)
subprocess.run('git commit -m "message"'.split(' '), cwd=base_path)
subprocess.run('git remote add origin https://github.com/openworm/pygeppetto.git'.split(" "), cwd=base_path)
subprocess.run('git fetch'.split(" "), cwd=base_path)
subprocess.run('git merge --allow-unrelated-histories origin/feature/46'.split(" "), cwd=base_path)
